# ========================================
# MultiScholaR Installation Script
# ========================================
# This script installs MultiScholaR by cloning the repository
# and detecting R installation paths.

cat("========================================\n")
cat("MultiScholaR Installation Script\n")
cat("========================================\n\n")

# Helper function to get Documents folder path
get_documents_path <- function() {
  os <- Sys.info()["sysname"]
  
  if (os == "Windows") {
    # Try USERPROFILE environment variable first
    user_profile <- Sys.getenv("USERPROFILE")
    if (user_profile != "") {
      docs_path <- file.path(user_profile, "Documents")
      if (dir.exists(docs_path)) {
        return(docs_path)
      }
    }
    # Fallback to home directory
    docs_path <- file.path(Sys.getenv("HOME"), "Documents")
  } else {
    # Mac/Linux
    docs_path <- file.path(Sys.getenv("HOME"), "Documents")
  }
  
  # Create Documents if it doesn't exist
  if (!dir.exists(docs_path)) {
    dir.create(docs_path, recursive = TRUE)
    cat("Created Documents directory:", docs_path, "\n")
  }
  
  return(docs_path)
}

# Helper function to detect R installation
detect_r_installation <- function() {
  os <- Sys.info()["sysname"]
  cat("Detecting R installation for", os, "...\n")
  
  # First, try to find Rscript in PATH
  rscript_path <- Sys.which("Rscript")
  if (rscript_path != "") {
    cat("Found Rscript in PATH:", rscript_path, "\n")
    return(rscript_path)
  }
  
  if (os == "Windows") {
    # Common Windows R installation locations
    possible_paths <- c(
      file.path(Sys.getenv("LOCALAPPDATA"), "Programs", "R"),
      "C:\\Program Files\\R",
      "C:\\Program Files (x86)\\R"
    )
    
    # Look for R-x.x.x directories and find Rscript.exe
    for (base_path in possible_paths) {
      if (dir.exists(base_path)) {
        r_dirs <- list.dirs(base_path, full.names = TRUE, recursive = FALSE)
        # Sort by name (newest first, assuming version numbering)
        r_dirs <- sort(r_dirs, decreasing = TRUE)
        
        for (r_dir in r_dirs) {
          rscript_exe <- file.path(r_dir, "bin", "Rscript.exe")
          if (file.exists(rscript_exe)) {
            cat("Found Rscript at:", rscript_exe, "\n")
            return(rscript_exe)
          }
        }
      }
    }
  } else {
    # Mac/Linux common locations
    possible_paths <- c(
      "/Library/Frameworks/R.framework/Resources/bin/Rscript",
      "/usr/local/bin/Rscript",
      "/usr/bin/Rscript",
      "/opt/homebrew/bin/Rscript"  # Apple Silicon Homebrew
    )
    
    for (rscript_path in possible_paths) {
      if (file.exists(rscript_path)) {
        cat("Found Rscript at:", rscript_path, "\n")
        return(rscript_path)
      }
    }
    
    # Try to find via R_HOME
    r_home <- Sys.getenv("R_HOME")
    if (r_home != "") {
      rscript_path <- file.path(r_home, "bin", "Rscript")
      if (file.exists(rscript_path)) {
        cat("Found Rscript via R_HOME:", rscript_path, "\n")
        return(rscript_path)
      }
    }
  }
  
  return(NULL)
}

# Helper function to check if git is available
check_git_available <- function() {
  git_check <- tryCatch({
    result <- system("git --version", intern = TRUE, ignore.stderr = TRUE)
    if (length(result) > 0 && grepl("git version", result[1])) {
      return(TRUE)
    }
    return(FALSE)
  }, error = function(e) {
    return(FALSE)
  })
  
  return(git_check)
}

# Helper function to read config file
read_config <- function(config_path) {
  if (!file.exists(config_path)) {
    return(NULL)
  }
  
  lines <- readLines(config_path, warn = FALSE)
  config <- list()
  
  for (line in lines) {
    line <- trimws(line)
    if (line == "" || grepl("^#", line)) {
      next  # Skip empty lines and comments
    }
    
    if (grepl("=", line)) {
      parts <- strsplit(line, "=", fixed = TRUE)[[1]]
      if (length(parts) == 2) {
        key <- trimws(parts[1])
        value <- trimws(parts[2])
        config[[key]] <- value
      }
    }
  }
  
  return(config)
}

# Helper function to write config file
write_config <- function(config_path, config_list) {
  lines <- character()
  lines <- c(lines, "# MultiScholaR Configuration File")
  lines <- c(lines, "# Generated by install_multischolar.R")
  lines <- c(lines, "")
  
  for (key in names(config_list)) {
    lines <- c(lines, paste0(key, "=", config_list[[key]]))
  }
  
  writeLines(lines, config_path)
  cat("Configuration saved to:", config_path, "\n")
}

# Main installation process
main <- function() {
  # Get launcher directory (where this script is located)
  # Try to get from command line args first (when run via Rscript)
  args <- commandArgs(trailingOnly = FALSE)
  script_path <- grep("^--file=", args, value = TRUE)
  if (length(script_path) > 0) {
    launcher_dir <- dirname(sub("^--file=", "", script_path))
    launcher_dir <- normalizePath(launcher_dir)
  } else {
    # Fallback: use current working directory
    # This happens when script is sourced in RStudio
    launcher_dir <- normalizePath(getwd())
  }
  cat("Launcher directory:", launcher_dir, "\n\n")
  
  # Check for git
  cat("Checking for git...\n")
  if (!check_git_available()) {
    stop("ERROR: git is not available. Please install git first.\n",
         "Windows: https://git-scm.com/download/win\n",
         "Mac: git should be available via Xcode Command Line Tools\n",
         "Run: xcode-select --install")
  }
  cat("✓ git is available\n\n")
  
  # Get Documents path
  cat("Determining Documents folder...\n")
  docs_path <- get_documents_path()
  cat("Documents folder:", docs_path, "\n\n")
  
  # Determine MultiScholaR installation path
  multischolar_path <- file.path(docs_path, "MultiScholaR")
  cat("MultiScholaR will be installed to:", multischolar_path, "\n")
  
  # Check if already exists
  if (dir.exists(multischolar_path)) {
    cat("\nWARNING: Directory already exists:", multischolar_path, "\n")
    cat("This appears to be an existing installation.\n")
    response <- readline("Do you want to update it? (y/n): ")
    if (tolower(substr(trimws(response), 1, 1)) != "y") {
      cat("Installation cancelled.\n")
      return(invisible(NULL))
    }
    cat("Updating existing installation...\n")
  } else {
    # Clone the repository
    cat("\nCloning MultiScholaR repository (v0.35.1 branch)...\n")
    repo_url <- "https://github.com/APAF-bioinformatics/MultiScholaR.git"
    branch <- "v0.35.1"
    
    clone_cmd <- paste("git clone -b", branch, repo_url, shQuote(multischolar_path))
    cat("Running:", clone_cmd, "\n")
    
    result <- system(clone_cmd)
    if (result != 0) {
      stop("ERROR: Failed to clone repository. Please check your internet connection and git installation.")
    }
    cat("✓ Repository cloned successfully\n\n")
  }
  
  # Detect R installation
  cat("Detecting R installation...\n")
  rscript_path <- detect_r_installation()
  if (is.null(rscript_path)) {
    stop("ERROR: Could not detect R installation. Please ensure R is installed and try again.")
  }
  cat("✓ R detected:", rscript_path, "\n\n")
  
  # Create config file
  config_path <- file.path(launcher_dir, "config.txt")
  config_list <- list(
    MULTISCHOLAR_PATH = normalizePath(multischolar_path),
    RSCRIPT_PATH = normalizePath(rscript_path),
    INSTALL_DATE = as.character(Sys.Date())
  )
  
  write_config(config_path, config_list)
  
  cat("\n========================================\n")
  cat("Installation completed successfully!\n")
  cat("========================================\n")
  cat("MultiScholaR path:", config_list$MULTISCHOLAR_PATH, "\n")
  cat("Rscript path:", config_list$RSCRIPT_PATH, "\n")
  cat("\nYou can now use the launcher scripts to run MultiScholaR.\n")
}

# Run installation
tryCatch({
  main()
}, error = function(e) {
  cat("\n========================================\n")
  cat("INSTALLATION FAILED\n")
  cat("========================================\n")
  cat("Error:", e$message, "\n")
  quit(status = 1)
})

